version: "3.2"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d/"
      - "$PWD/mysql/logs:/logs"
    ports:
      - "3306:3306"
    restart: always

  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
    restart: always
    depends_on:
      - mysql

  nacos2:
    hostname: nacos2
    container_name: nacos2
    image: nacos/nacos-server:latest
    environment:
      MODE: standalone
    ports:
      - "8847:8848"
    restart: always
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - "$PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "$PWD/nginx/html:/usr/share/nginx/html"
      - "$PWD/nginx/logs:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - nacos1
      - nacos2



  gateway:
    build: ./gateway
    ports:
      - "9000:9000"
    depends_on:
      - nacos1
      - nacos2
      - nginx

  admin:
    image: renren/renren-admin
    ports:
      - "8080:8080"
#    environment:
#      - spring.profiles.active=dev
    depends_on:
      - nacos1
      - nacos2
      - nginx

#  renren-api:
#    image: renren/renren-api
#    ports:
#      - "8081:8081"
#    environment:
#      - spring.profiles.active=dev
#    depends_on:
#      - nacos1
#      - nacos2
#      - nginx

  project-menber:
    build: ./project-menber
    depends_on:
      - nacos1
      - nacos2
      - nginx

  project-product:
    build: ./project-product
    depends_on:
      - nacos1
      - nacos2
      - nginx

  project-order:
    build: ./project-order
    depends_on:
      - nacos1
      - nacos2
      - nginx

  project-ware:
    build: ./project-ware
    depends_on:
      - nacos1
      - nacos2
      - nginx

  project-coupon:
    build: ./project-coupon
    depends_on:
      - nacos1
      - nacos2
      - nginx

  es1:
    image: elasticsearch:7.12.1
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es2
      - cluster.initial_master_nodes=es1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "$PWD/elasticsearch/data/1:/usr/share/elasticsearch/data"
      - "$PWD/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
      - "$PWD/elasticsearch/config/1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - 9200:9200
    networks:
      - elastic

  es2:
    image: elasticsearch:7.12.1
    container_name: es2
    environment:
      - node.name=es2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es1
      - cluster.initial_master_nodes=es1,es2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "$PWD/elasticsearch/data/2:/usr/share/elasticsearch/data"
      - "$PWD/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
    networks:
      - elastic

  redis-master-1:
    image: redis
    container_name: redis-master-1
    restart: always
    volumes:
      - "$PWD/redis/master1/data:/data"
      - "$PWD/redis/master1/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"

  redis-master-2:
    image: redis
    container_name: redis-master-2
    restart: always
    volumes:
      - "$PWD/redis/master2/data:/data"
      - "$PWD/redis/master2/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"

  redis-master-3:
    image: redis
    container_name: redis-master-3
    restart: always
    volumes:
      - "$PWD/redis/master3/data:/data"
      - "$PWD/redis/master3/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"

  redis-slave-1:
    image: redis
    container_name: redis-slave-1
    restart: always
    volumes:
      - "$PWD/redis/slave1/data:/data"
      - "$PWD/redis/slave1/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    depends_on:
      - redis-master-1

  redis-slave-2:
    image: redis
    container_name: redis-slave-2
    restart: always
    volumes:
      - "$PWD/redis/slave2/data:/data"
      - "$PWD/redis/slave2/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    depends_on:
      - redis-master-2

  redis-slave-3:
    image: redis
    container_name: redis-slave-3
    restart: always
    volumes:
      - "$PWD/redis/slave3/data:/data"
      - "$PWD/redis/slave3/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    depends_on:
      - redis-master-3

networks:
  elastic:
    driver: bridge


