### ----本地配置----
server:
  port: 9000 # 网关端口
spring:
  application:
    name: project-gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.145.101:80 # nacos地址
      discovery:
        namespace: dev666
    gateway:
      routes: # 网关路由配置
        - id: qq # 路由id，自定义，只要唯一即可
          uri: https://www.qq.com # 路由的目标地址 http就是固定地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/qq/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: project-coupon # 路由id，自定义，只要唯一即可
          # uri: http://localhost:9401 # 路由的目标地址 http就是固定地址
          uri: lb://project-coupon # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/coupon/** # 这个是按照路径匹配，只要以/user/开头就符合要求
